version: '3'

# Создаем общую сеть deafult для всех контейнеров
networks:
  default:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # Подключаем к общей сети с другими контейнерами
    networks:
      - default
    # Запускаем только после db
    depends_on:
      - db
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-enabled/default
      - ./docker/php/user.ini:/etc/php/7.2/fpm/user.ini
      #- ./docker/php/php-fpm.conf:/etc/php/7.2/fpm/pool.d/www.conf
      - .:/home/apps/site
    ports:
      - "8080:80"
  # Контейнер с базой данных
  db:
    image: mysql:5.6.51
    # Подключаем к общей сети с другими контейнерами
    networks:
      - default
    # Показываем наружу порт
    ports:
      - "3336:3306"
    # Задаем параметры для инициализации БД
    environment:
      # Пароль к БД
      MYSQL_ROOT_PASSWORD: root
      # Создаваемая по умолчанию бд
      MYSQL_DATABASE: db
    # Линкуем внешнюю папку для хранения БД
    volumes:
      - mysql-data:/var/lib/mysql"
volumes:
  mysql-data:
    driver: local